dist:
  name: otelcol-nats
  description: OpenTelemetry Collector with NATS receiver
  output_path: ./build
  otelcol_version: 0.143.0

receivers:
  - gomod: github.com/Bre77/otel-nats-receiver/receiver v0.0.0
    path: ./receiver

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.143.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.143.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.143.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.143.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.143.0
